# 网站基本信息
title: ROC
description: 个人导航 · 开发工具 & 资源收录
author: reroc8
favicon: menav.svg
logo_text: ROC

icons:
  mode: favicon
  region: cn

theme:
  mode: system

fonts:
  source: css
  cssUrl: 'https://fontsapi.zeoseven.com/292/main/result.css'
  preload: true
  family: LXGW WenKai
  weight: normal

profile:
  title: Hey,
  subtitle: 探索无界

github:
  username: 'reroc8'
  heatmapColor: 37b24d
  cacheDir: dev

social:
  - name: GitHub
    url: https://github.com/reroc8
    icon: fab fa-github
  - name: Email
    url: mailto:reroc8@gmail.com
    icon: fas fa-envelope

# 导航：常用 | 项目 | 关于
navigation:
  - name: 常用
    icon: fas fa-star
    id: common
  - name: 项目
    icon: fas fa-project-diagram
    id: projects
  - name: 关于
    icon: fas fa-file-alt
    id: content
